Fix config file parsing
swaywm/swayidle pull request #86
Opened 2020-11-05 22:08 UTC by apiraino

Hi!

Would this patch fix #70?

thanks for the review (and sorry for the perhaps poor quality of my patch)

2020-11-05 22:22 UTC, emersion requested changes
Thanks for sending a patch, the logic LGTM!

Can you edit your commit message to include more information? Maybe something among these lines:

```
Fix last character of config file dropped

getline returns a string without a newline if the config file doesn't have a final newline.

Closes: #70 
```

2020-11-05 22:22 UTC, emersion commented on main.c
> +                if (line[nread-1] == '\n')
Style: we use tabs, not spaces

2020-11-05 22:22 UTC, emersion commented on main.c
> +                if (line[nread-1] == '\n')
Style: braces are mandatory

2020-11-06 09:07 UTC, apiraino commented on main.c
> +                if (line[nread-1] == '\n')
the github editor caught me offguard :)

2020-11-06 09:08 UTC, emersion commented
Can you squash these two commits together? See https://git-rebase.io/

2020-11-06 10:02 UTC, apiraino commented
> Can you squash these two commits together? See https://git-rebase.io/

yes I can ... (I thought you could squash+merge directly from github)

2020-11-06 10:36 UTC, apiraino commented
superseded by #87

2020-11-06 10:36 UTC, closed without merging

2020-11-06 10:37 UTC, emersion commented
There's no need to close the PR. You can force-push to your branch instead.